/* prettier-ignore */
import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateDatabaseTables1760553234295 implements MigrationInterface {
    name = 'CreateDatabaseTables1760553234295'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "service_request_entity" DROP CONSTRAINT "FK_3d82297b1a61162ebab998fe8ee"`);
        await queryRunner.query(`ALTER TABLE "service_request_entity" DROP CONSTRAINT "FK_7973b8164ebee81efb2d3dea95a"`);
        await queryRunner.query(`ALTER TABLE "service_request_entity" DROP CONSTRAINT "FK_5b2cadf701ee3a20b7c3dfd368d"`);
        await queryRunner.query(`ALTER TABLE "service_request_entity" DROP CONSTRAINT "FK_e72e2a6915d72117c8f9ca2c195"`);
        // await queryRunner.query(`DROP INDEX "TBLCATEMP$ClientesIdClientes" ON "TBLCATEMP"`);
        // await queryRunner.query(`DROP INDEX "TBLCATEMP$Id" ON "TBLCATEMP"`);
        // await queryRunner.query(`DROP INDEX "TBLTRNVHC_CP$LNGCLVSTP" ON "TBLTRNVHC_CP"`);
        // await queryRunner.query(`DROP INDEX "TBLTRNVHC_CP$STRCLVTPV" ON "TBLTRNVHC_CP"`);
        await queryRunner.query(`EXEC sp_rename "BD_TALLER.dbo.service_request_entity.vehicleEntityId", "vehicleId"`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uniqueidentifier NOT NULL, "hashedPassword" nvarchar(60), "email" nvarchar(255) NOT NULL, "isActive" bit NOT NULL CONSTRAINT "DF_fde2ce12ab12b02ae583dd76c7c" DEFAULT 1, "encryptedTokenSecret" varbinary(255) NOT NULL, "createdAt" datetime NOT NULL CONSTRAINT "DF_e11e649824a45d8ed01d597fd93" DEFAULT getdate(), "updatedAt" datetime NOT NULL CONSTRAINT "DF_80ca6e6ef65fb9ef34ea8c90f42" DEFAULT getdate(), "employeeId" int, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "work_order_diagnostic" ("id" uniqueidentifier NOT NULL, "reportedSymptoms" nvarchar(255) NOT NULL, "impactsOperability" bit NOT NULL, "issueFrequency" nvarchar(25) NOT NULL, "technicalDescription" nvarchar(255), "affectedSystems" nvarchar(255), "requiredMaterials" nvarchar(255), "reportedByDriverId" int NOT NULL, CONSTRAINT "PK_c03c81cfc9adeb4a5fb6351fa99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "work_order_service" ("id" uniqueidentifier NOT NULL, "fuelLevelAtReception" int, "mileageAtReception" int, "receivedInventoryItems" nvarchar(255), "roofObservations" nvarchar(255), "frontObservations" nvarchar(255), "leftSideObservations" nvarchar(255), "rightSideObservations" nvarchar(255), "rearObservations" nvarchar(255), "performedServices" nvarchar(255), "installedReplacementParts" nvarchar(255), "addedFluids" nvarchar(255), CONSTRAINT "PK_f1d2c3ac58db328d26068b8267d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "work_order" ("id" uniqueidentifier NOT NULL, "type" nvarchar(25), "scheduledDate" datetime, "estimatedDuration" datetime, "actualDuration" datetime, "vehicleInWorkshop" bit, "requiresApproval" bit NOT NULL CONSTRAINT "DF_6e309ccc9cf4db566abc94430b8" DEFAULT 1, "approvalDate" datetime, "status" nvarchar(25) NOT NULL, "workshopId" uniqueidentifier NOT NULL, "scheduledById" uniqueidentifier, "supervisorId" int, "assignedEmployeeId" int, CONSTRAINT "PK_0730e63dd523d397530859cb6d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customer" ("id" uniqueidentifier NOT NULL, "name" nvarchar(255) NOT NULL, "type" nvarchar(25) NOT NULL, "createdAt" datetime NOT NULL CONSTRAINT "DF_6042277b62323ae370b2d796819" DEFAULT getdate(), "updatedAt" datetime NOT NULL CONSTRAINT "DF_0d1052d66fcdaf80d9587e4fb7f" DEFAULT getdate(), CONSTRAINT "PK_a7a13f4cacb744524e44dfdad32" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "group" ("id" uniqueidentifier NOT NULL, "name" nvarchar(100) NOT NULL, "isActive" bit NOT NULL CONSTRAINT "DF_8f52531f358c41f38973fd631f1" DEFAULT 1, "permissions" text, "createdAt" datetime NOT NULL CONSTRAINT "DF_1d82a7a787f7a9cc24cff3abe74" DEFAULT getdate(), "updatedAt" datetime NOT NULL CONSTRAINT "DF_f01d767a686ac4c224f768be2c4" DEFAULT getdate(), CONSTRAINT "UQ_8a45300fd825918f3b40195fbdc" UNIQUE ("name"), CONSTRAINT "PK_256aa0fda9b1de1a73ee0b7106b" PRIMARY KEY ("id"))`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "Nombre"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "SSMA_TimeStamp"`);
        await queryRunner.query(`ALTER TABLE "workshop" ADD "createdAt" datetime NOT NULL CONSTRAINT "DF_185f87afcb1c425399a7911a47c" DEFAULT getdate()`);
        await queryRunner.query(`ALTER TABLE "workshop" ADD "updatedAt" datetime NOT NULL CONSTRAINT "DF_b2d9cf1e979b6eca3855f7a6082" DEFAULT getdate()`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "PK_dc2b08a8089f60a105b512ba22a"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "LNGCLVEMP"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "LNGCLVEMP" int NOT NULL`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "PK_dc2b08a8089f60a105b512ba22a" PRIMARY KEY ("LNGCLVEMP")`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "DF_2e58de69cf290138a0e962064c9"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRLOCEMP"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRLOCEMP" nvarchar(150)`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRNSSEMP"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRNSSEMP" nvarchar(50)`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRDPTEMP"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRDPTEMP" nvarchar(255)`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRPSTEMP"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRPSTEMP" nvarchar(255)`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "DF_e4d4c750aca056535da18661a2e"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRNCKEMP"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRNCKEMP" nvarchar(100)`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRPWSEMP"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRPWSEMP" nvarchar(100)`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "DF_49dbd50580e9983db1ec9044de0"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "DF_3c97cd8ff29381805a72e75c205"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "DF_13281011937dd948cc4b9ac3300"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "DF_9367a38e49f123e9b0de7ad84da"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "DTFCHRGS"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "DTFCHRGS" nvarchar(10)`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "DF_a09f6241950cd294134034b0558"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "LNGCLVMPL_RGS"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "LNGCLVMPL_RGS" int`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "DF_06b9e50b914f784b17ffa194bb7"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "DTFCHPDT"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "DTFCHPDT" nvarchar(10)`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "DF_50e8689f5343b41b3569fa6ef7b"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "LNGCLVMPL_PDT"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "LNGCLVMPL_PDT" int`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "DF_c2a36047c72d71b7d6c0d635c5f"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "PK_164f7f5ae561a5ae8f96953dd3d"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP COLUMN "LNGDNTTRN"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD "LNGDNTTRN" int NOT NULL`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "PK_164f7f5ae561a5ae8f96953dd3d" PRIMARY KEY ("LNGDNTTRN")`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ALTER COLUMN "STRCLVTPV" nvarchar(10)`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_3f24815b7736116482437a866b3"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP COLUMN "STRNSRTRN"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD "STRNSRTRN" nvarchar(20)`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_3af4fa2fe5c31d4ad67e22fac96"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_289616fd56b2a1488d46c28f3ac"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_e8f84c29c6e03c619d9ec3b612e"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_3ae82008596e745ab3b9dd9c557"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_a87f8543bac64b3c42c98689b6a"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ALTER COLUMN "DTFCHRGS" datetime2(0) NOT NULL`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_54f3ecbc0dcb0ab6fc75975fc48" DEFAULT getdate() FOR "DTFCHRGS"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_a8731d6aea6da718ee88b8ba0fe"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_580523d57b2cb59c3bf376e785c"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ALTER COLUMN "DTFCHPDT" datetime2(0) NOT NULL`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_eb00fdafc6c2c25a99d88919aba" DEFAULT getdate() FOR "DTFCHPDT"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_3bd8bded47d258f20cfea432def"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_1e1a1c7bbde58d1d9accda7c866"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP COLUMN "SSMA_TimeStamp"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD "SSMA_TimeStamp" int NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_ab4a80281f1e8d524714e00f38f" FOREIGN KEY ("employeeId") REFERENCES "TBLCATEMP"("LNGCLVEMP") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order_diagnostic" ADD CONSTRAINT "FK_93f970533c1c0cd6cb757bc23ab" FOREIGN KEY ("reportedByDriverId") REFERENCES "TBLCATEMP"("LNGCLVEMP") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order" ADD CONSTRAINT "FK_ee413bb613b090c056af0a38828" FOREIGN KEY ("workshopId") REFERENCES "workshop"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order" ADD CONSTRAINT "FK_365e7a0afd13a4496b278ea7d2a" FOREIGN KEY ("scheduledById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order" ADD CONSTRAINT "FK_2bc2301df5597a6779352988b6e" FOREIGN KEY ("supervisorId") REFERENCES "TBLCATEMP"("LNGCLVEMP") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order" ADD CONSTRAINT "FK_cd0167d4f048758199744e2ac3a" FOREIGN KEY ("assignedEmployeeId") REFERENCES "TBLCATEMP"("LNGCLVEMP") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_request_entity" ADD CONSTRAINT "FK_7973b8164ebee81efb2d3dea95a" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_request_entity" ADD CONSTRAINT "FK_5b2cadf701ee3a20b7c3dfd368d" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_request_entity" ADD CONSTRAINT "FK_e72e2a6915d72117c8f9ca2c195" FOREIGN KEY ("requesterId") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_request_entity" ADD CONSTRAINT "FK_c519a33ac7c4e9e014315da2ddd" FOREIGN KEY ("vehicleId") REFERENCES "TBLTRNVHC_CP"("LNGDNTTRN") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "service_request_entity" DROP CONSTRAINT "FK_c519a33ac7c4e9e014315da2ddd"`);
        await queryRunner.query(`ALTER TABLE "service_request_entity" DROP CONSTRAINT "FK_e72e2a6915d72117c8f9ca2c195"`);
        await queryRunner.query(`ALTER TABLE "service_request_entity" DROP CONSTRAINT "FK_5b2cadf701ee3a20b7c3dfd368d"`);
        await queryRunner.query(`ALTER TABLE "service_request_entity" DROP CONSTRAINT "FK_7973b8164ebee81efb2d3dea95a"`);
        await queryRunner.query(`ALTER TABLE "work_order" DROP CONSTRAINT "FK_cd0167d4f048758199744e2ac3a"`);
        await queryRunner.query(`ALTER TABLE "work_order" DROP CONSTRAINT "FK_2bc2301df5597a6779352988b6e"`);
        await queryRunner.query(`ALTER TABLE "work_order" DROP CONSTRAINT "FK_365e7a0afd13a4496b278ea7d2a"`);
        await queryRunner.query(`ALTER TABLE "work_order" DROP CONSTRAINT "FK_ee413bb613b090c056af0a38828"`);
        await queryRunner.query(`ALTER TABLE "work_order_diagnostic" DROP CONSTRAINT "FK_93f970533c1c0cd6cb757bc23ab"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_ab4a80281f1e8d524714e00f38f"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP COLUMN "SSMA_TimeStamp"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD "SSMA_TimeStamp" timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_1e1a1c7bbde58d1d9accda7c866" DEFAULT 0 FOR "LNGCLVQPM_PDT"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_3bd8bded47d258f20cfea432def" DEFAULT 0 FOR "LNGCLVMPL_PDT"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_eb00fdafc6c2c25a99d88919aba"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ALTER COLUMN "DTFCHPDT" datetime2(0)`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_580523d57b2cb59c3bf376e785c" DEFAULT 0 FOR "LNGCLVQPM_RGS"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_a8731d6aea6da718ee88b8ba0fe" DEFAULT 0 FOR "LNGCLVMPL_RGS"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_54f3ecbc0dcb0ab6fc75975fc48"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ALTER COLUMN "DTFCHRGS" datetime2(0)`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_a87f8543bac64b3c42c98689b6a" DEFAULT 0 FOR "MNDIMPADQ"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_3ae82008596e745ab3b9dd9c557" DEFAULT 0 FOR "LNGCLVCHF"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_e8f84c29c6e03c619d9ec3b612e" DEFAULT 0 FOR "LNGCLVENT"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_289616fd56b2a1488d46c28f3ac" DEFAULT 0 FOR "LNGKLMVHC"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_3af4fa2fe5c31d4ad67e22fac96" DEFAULT 0 FOR "DCMPBRTRN"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP COLUMN "STRNSRTRN"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD "STRNSRTRN" nvarchar(17)`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_3f24815b7736116482437a866b3" DEFAULT 0 FOR "LNGCLVSTP"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ALTER COLUMN "STRCLVTPV" nvarchar(10) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "PK_164f7f5ae561a5ae8f96953dd3d"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP COLUMN "LNGDNTTRN"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD "LNGDNTTRN" int NOT NULL IDENTITY(1,1)`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "PK_164f7f5ae561a5ae8f96953dd3d" PRIMARY KEY ("LNGDNTTRN")`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "DF_c2a36047c72d71b7d6c0d635c5f" DEFAULT 0 FOR "LNGCLVQPM_PDT"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "LNGCLVMPL_PDT"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "LNGCLVMPL_PDT" float`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "DF_50e8689f5343b41b3569fa6ef7b" DEFAULT 0 FOR "LNGCLVMPL_PDT"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "DTFCHPDT"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "DTFCHPDT" nvarchar(25)`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "DF_06b9e50b914f784b17ffa194bb7" DEFAULT 0 FOR "LNGCLVQPM_RGS"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "LNGCLVMPL_RGS"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "LNGCLVMPL_RGS" float`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "DF_a09f6241950cd294134034b0558" DEFAULT 0 FOR "LNGCLVMPL_RGS"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "DTFCHRGS"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "DTFCHRGS" nvarchar(25)`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "DF_9367a38e49f123e9b0de7ad84da" DEFAULT 0 FOR "LNGCLVMPL_BLQ"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "DF_13281011937dd948cc4b9ac3300" DEFAULT 0 FOR "BLNBLQRGS"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "DF_3c97cd8ff29381805a72e75c205" DEFAULT 0 FOR "Suspendido"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "DF_49dbd50580e9983db1ec9044de0" DEFAULT 0 FOR "DBLPRCDST"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRPWSEMP"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRPWSEMP" nvarchar(10)`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRNCKEMP"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRNCKEMP" nvarchar(50)`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "DF_e4d4c750aca056535da18661a2e" DEFAULT 0 FOR "BLNUSREMP"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRPSTEMP"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRPSTEMP" nvarchar(50)`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRDPTEMP"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRDPTEMP" nvarchar(50)`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRNSSEMP"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRNSSEMP" nvarchar(15)`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRLOCEMP"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRLOCEMP" nvarchar(50)`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "DF_2e58de69cf290138a0e962064c9" DEFAULT 0 FOR "LNGNOEMP"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "PK_dc2b08a8089f60a105b512ba22a"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "LNGCLVEMP"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "LNGCLVEMP" int NOT NULL IDENTITY(1,1)`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "PK_dc2b08a8089f60a105b512ba22a" PRIMARY KEY ("LNGCLVEMP")`);
        await queryRunner.query(`ALTER TABLE "workshop" DROP CONSTRAINT "DF_b2d9cf1e979b6eca3855f7a6082"`);
        await queryRunner.query(`ALTER TABLE "workshop" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "workshop" DROP CONSTRAINT "DF_185f87afcb1c425399a7911a47c"`);
        await queryRunner.query(`ALTER TABLE "workshop" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "SSMA_TimeStamp" timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "Nombre" nvarchar(50)`);
        await queryRunner.query(`DROP TABLE "group"`);
        await queryRunner.query(`DROP TABLE "customer"`);
        await queryRunner.query(`DROP TABLE "work_order"`);
        await queryRunner.query(`DROP TABLE "work_order_service"`);
        await queryRunner.query(`DROP TABLE "work_order_diagnostic"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`EXEC sp_rename "BD_TALLER.dbo.service_request_entity.vehicleId", "vehicleEntityId"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "TBLTRNVHC_CP$STRCLVTPV" ON "TBLTRNVHC_CP" ("STRCLVTPV") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "TBLTRNVHC_CP$LNGCLVSTP" ON "TBLTRNVHC_CP" ("LNGCLVSTP") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "TBLCATEMP$Id" ON "TBLCATEMP" ("LNGCLVEMP") `);
        await queryRunner.query(`CREATE INDEX "TBLCATEMP$ClientesIdClientes" ON "TBLCATEMP" ("LNGNOEMP") `);
        await queryRunner.query(`ALTER TABLE "service_request_entity" ADD CONSTRAINT "FK_e72e2a6915d72117c8f9ca2c195" FOREIGN KEY ("requesterId") REFERENCES "customer_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_request_entity" ADD CONSTRAINT "FK_5b2cadf701ee3a20b7c3dfd368d" FOREIGN KEY ("updatedById") REFERENCES "user_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_request_entity" ADD CONSTRAINT "FK_7973b8164ebee81efb2d3dea95a" FOREIGN KEY ("createdById") REFERENCES "user_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_request_entity" ADD CONSTRAINT "FK_3d82297b1a61162ebab998fe8ee" FOREIGN KEY ("vehicleEntityId") REFERENCES "TBLTRNVHC_CP"("LNGDNTTRN") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
/* prettier-ignore */
