/* prettier-ignore */
import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateDatabaseTables1760488404058 implements MigrationInterface {
    name = 'CreateDatabaseTables1760488404058'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // await queryRunner.query(`DROP INDEX "TBLCATEMP$ClientesIdClientes" ON "TBLCATEMP"`);
        // await queryRunner.query(`DROP INDEX "TBLCATEMP$Id" ON "TBLCATEMP"`);
        // await queryRunner.query(`DROP INDEX "TBLTRNVHC_CP$LNGCLVSTP" ON "TBLTRNVHC_CP"`);
        // await queryRunner.query(`DROP INDEX "TBLTRNVHC_CP$STRCLVTPV" ON "TBLTRNVHC_CP"`);
        await queryRunner.query(`CREATE TABLE "workshop" ("id" uniqueidentifier NOT NULL, "name" nvarchar(255) NOT NULL, "capacity" int NOT NULL, CONSTRAINT "PK_e755b83ccf7c711f998012e1c92" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "workshop_entity" ("id" uniqueidentifier NOT NULL, "name" nvarchar(255) NOT NULL, "capacity" int NOT NULL, "createdAt" datetime NOT NULL CONSTRAINT "DF_2696fa4a0f0781a36ddd7f1f3b4" DEFAULT getdate(), "updatedAt" datetime NOT NULL CONSTRAINT "DF_50cded9c08ab730cc604ed3bc03" DEFAULT getdate(), CONSTRAINT "PK_4f57ba91f6201044b664cd4a9c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_entity" ("id" uniqueidentifier NOT NULL, "hashedPassword" nvarchar(60), "email" nvarchar(255) NOT NULL, "isActive" bit NOT NULL CONSTRAINT "DF_d8964a43ebb5c941c14a229adb8" DEFAULT 1, "encryptedTokenSecret" varbinary(255) NOT NULL, "createdAt" datetime NOT NULL CONSTRAINT "DF_73d93da5d7e1af5e2171d9f4543" DEFAULT getdate(), "updatedAt" datetime NOT NULL CONSTRAINT "DF_47a12bfe17e970e3f22fc3e4c01" DEFAULT getdate(), "employeeEntityId" int, CONSTRAINT "PK_b54f8ea623b17094db7667d8206" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "group_entity" ("id" uniqueidentifier NOT NULL, "name" nvarchar(100) NOT NULL, "isActive" bit NOT NULL CONSTRAINT "DF_41769e0df2b1bd41390a1408207" DEFAULT 1, "permissions" text, "createdAt" datetime NOT NULL CONSTRAINT "DF_0ac89536afc26882dfa84e1f330" DEFAULT getdate(), "updatedAt" datetime NOT NULL CONSTRAINT "DF_b14426b7e3c43d92c072e890f75" DEFAULT getdate(), CONSTRAINT "UQ_0bd21227754816190ee2ea0fb20" UNIQUE ("name"), CONSTRAINT "PK_d074114199e1996b57b04ac77ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customer_entity" ("id" uniqueidentifier NOT NULL, "name" nvarchar(255) NOT NULL, "type" nvarchar(25) NOT NULL, "createdAt" datetime NOT NULL CONSTRAINT "DF_913e686ead5d737723c6ad7e5c2" DEFAULT getdate(), "updatedAt" datetime NOT NULL CONSTRAINT "DF_24c12b2d131518f09ba09e0e954" DEFAULT getdate(), CONSTRAINT "PK_8898b6830f057f3f5c239796fa7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "service_request_entity" ("id" uniqueidentifier NOT NULL, "trackingCode" nvarchar(10) NOT NULL, "priority" nvarchar(25) NOT NULL, "createdAt" datetime NOT NULL CONSTRAINT "DF_2ea637e0d1638e627ca2349013d" DEFAULT getdate(), "updatedAt" datetime NOT NULL CONSTRAINT "DF_881b0f6271ff6383a6e3b6662c9" DEFAULT getdate(), "createdById" uniqueidentifier NOT NULL, "updatedById" uniqueidentifier NOT NULL, "requesterId" uniqueidentifier NOT NULL, "vehicleEntityId" int NOT NULL, CONSTRAINT "PK_6ddb9ad7359a4c9a3727e6445c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "work_order_entity" ("id" uniqueidentifier NOT NULL, "scheduledDate" datetime, "estimatedDuration" datetime, "actualDuration" datetime, "vehicleInWorkshop" bit, "requiresApproval" bit NOT NULL CONSTRAINT "DF_8ac3fbdc58c8ce9da2d8499fc46" DEFAULT 1, "approvalDate" datetime, "status" nvarchar(25) NOT NULL, "serviceRequestEntityId" uniqueidentifier NOT NULL, "workshopEntityId" uniqueidentifier NOT NULL, "scheduledById" uniqueidentifier, "supervisorId" int, "assignedEmployeeEntityId" int, CONSTRAINT "PK_21f5736a602202482df7b9b9c86" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "work_order_service_entity" ("id" uniqueidentifier NOT NULL, "fuelLevelAtReception" int, "mileageAtReception" int, "receivedInventoryItems" nvarchar(255), "roofObservations" nvarchar(255), "frontObservations" nvarchar(255), "leftSideObservations" nvarchar(255), "rightSideObservations" nvarchar(255), "rearObservations" nvarchar(255), "performedServices" nvarchar(255), "installedReplacementParts" nvarchar(255), "addedFluids" nvarchar(255), "workOrderEntityId" uniqueidentifier NOT NULL, CONSTRAINT "PK_b4d8911f86862632df528243267" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "work_order_diagnostic_entity" ("id" uniqueidentifier NOT NULL, "reportedSymptoms" nvarchar(255) NOT NULL, "impactsOperability" bit NOT NULL, "issueFrequency" nvarchar(25) NOT NULL, "technicalDescription" nvarchar(255), "affectedSystems" nvarchar(255), "requiredMaterials" nvarchar(255), "workOrderEntityId" uniqueidentifier NOT NULL, "reportedByDriverId" int NOT NULL, CONSTRAINT "PK_524bf89ca783466ca9b2e9daba2" PRIMARY KEY ("id"))`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "Nombre"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "SSMA_TimeStamp"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "PK_dc2b08a8089f60a105b512ba22a"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "LNGCLVEMP"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "LNGCLVEMP" int NOT NULL`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "PK_dc2b08a8089f60a105b512ba22a" PRIMARY KEY ("LNGCLVEMP")`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "DF_2e58de69cf290138a0e962064c9"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRLOCEMP"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRLOCEMP" nvarchar(150)`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRNSSEMP"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRNSSEMP" nvarchar(50)`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRDPTEMP"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRDPTEMP" nvarchar(255)`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRPSTEMP"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRPSTEMP" nvarchar(255)`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "DF_e4d4c750aca056535da18661a2e"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRNCKEMP"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRNCKEMP" nvarchar(100)`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRPWSEMP"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRPWSEMP" nvarchar(100)`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "DF_49dbd50580e9983db1ec9044de0"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "DF_3c97cd8ff29381805a72e75c205"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "DF_13281011937dd948cc4b9ac3300"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "DF_9367a38e49f123e9b0de7ad84da"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "DTFCHRGS"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "DTFCHRGS" nvarchar(10)`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "DF_a09f6241950cd294134034b0558"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "LNGCLVMPL_RGS"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "LNGCLVMPL_RGS" int`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "DF_06b9e50b914f784b17ffa194bb7"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "DTFCHPDT"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "DTFCHPDT" nvarchar(10)`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "DF_50e8689f5343b41b3569fa6ef7b"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "LNGCLVMPL_PDT"`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "LNGCLVMPL_PDT" int`);
        // await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "DF_c2a36047c72d71b7d6c0d635c5f"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP COLUMN "LNGDNTTRN"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD "LNGDNTTRN" int NOT NULL`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "PK_164f7f5ae561a5ae8f96953dd3d" PRIMARY KEY ("LNGDNTTRN")`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ALTER COLUMN "STRCLVTPV" nvarchar(10)`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_3f24815b7736116482437a866b3"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP COLUMN "STRNSRTRN"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD "STRNSRTRN" nvarchar(20)`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_3af4fa2fe5c31d4ad67e22fac96"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_289616fd56b2a1488d46c28f3ac"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_e8f84c29c6e03c619d9ec3b612e"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_3ae82008596e745ab3b9dd9c557"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_a87f8543bac64b3c42c98689b6a"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ALTER COLUMN "DTFCHRGS" datetime2(0) NOT NULL`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_54f3ecbc0dcb0ab6fc75975fc48" DEFAULT getdate() FOR "DTFCHRGS"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_a8731d6aea6da718ee88b8ba0fe"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_580523d57b2cb59c3bf376e785c"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ALTER COLUMN "DTFCHPDT" datetime2(0) NOT NULL`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_eb00fdafc6c2c25a99d88919aba" DEFAULT getdate() FOR "DTFCHPDT"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_3bd8bded47d258f20cfea432def"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_1e1a1c7bbde58d1d9accda7c866"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP COLUMN "SSMA_TimeStamp"`);
        // await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD "SSMA_TimeStamp" int NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_entity" ADD CONSTRAINT "FK_14e995b917d5c6bb8d2d4e9b546" FOREIGN KEY ("employeeEntityId") REFERENCES "TBLCATEMP"("LNGCLVEMP") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_request_entity" ADD CONSTRAINT "FK_7973b8164ebee81efb2d3dea95a" FOREIGN KEY ("createdById") REFERENCES "user_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_request_entity" ADD CONSTRAINT "FK_5b2cadf701ee3a20b7c3dfd368d" FOREIGN KEY ("updatedById") REFERENCES "user_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_request_entity" ADD CONSTRAINT "FK_e72e2a6915d72117c8f9ca2c195" FOREIGN KEY ("requesterId") REFERENCES "customer_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_request_entity" ADD CONSTRAINT "FK_3d82297b1a61162ebab998fe8ee" FOREIGN KEY ("vehicleEntityId") REFERENCES "TBLTRNVHC_CP"("LNGDNTTRN") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order_entity" ADD CONSTRAINT "FK_ced5736c7fe2fa52a344f6d2abb" FOREIGN KEY ("serviceRequestEntityId") REFERENCES "service_request_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order_entity" ADD CONSTRAINT "FK_46907166ae6a4c26c13c4dd3083" FOREIGN KEY ("workshopEntityId") REFERENCES "workshop_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order_entity" ADD CONSTRAINT "FK_089c44d57682fc4396e445976d4" FOREIGN KEY ("scheduledById") REFERENCES "user_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order_entity" ADD CONSTRAINT "FK_86399ffe83dc6a2f171aa61f3de" FOREIGN KEY ("supervisorId") REFERENCES "TBLCATEMP"("LNGCLVEMP") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order_entity" ADD CONSTRAINT "FK_3c2f9c03e0fbc2f589a10d498eb" FOREIGN KEY ("assignedEmployeeEntityId") REFERENCES "TBLCATEMP"("LNGCLVEMP") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order_service_entity" ADD CONSTRAINT "FK_f46b22805297a408bdef267436b" FOREIGN KEY ("workOrderEntityId") REFERENCES "work_order_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order_diagnostic_entity" ADD CONSTRAINT "FK_68baf4088a1def5994fad729c01" FOREIGN KEY ("workOrderEntityId") REFERENCES "work_order_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order_diagnostic_entity" ADD CONSTRAINT "FK_9c3456cd935ab41139ee7428372" FOREIGN KEY ("reportedByDriverId") REFERENCES "TBLCATEMP"("LNGCLVEMP") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "work_order_diagnostic_entity" DROP CONSTRAINT "FK_9c3456cd935ab41139ee7428372"`);
        await queryRunner.query(`ALTER TABLE "work_order_diagnostic_entity" DROP CONSTRAINT "FK_68baf4088a1def5994fad729c01"`);
        await queryRunner.query(`ALTER TABLE "work_order_service_entity" DROP CONSTRAINT "FK_f46b22805297a408bdef267436b"`);
        await queryRunner.query(`ALTER TABLE "work_order_entity" DROP CONSTRAINT "FK_3c2f9c03e0fbc2f589a10d498eb"`);
        await queryRunner.query(`ALTER TABLE "work_order_entity" DROP CONSTRAINT "FK_86399ffe83dc6a2f171aa61f3de"`);
        await queryRunner.query(`ALTER TABLE "work_order_entity" DROP CONSTRAINT "FK_089c44d57682fc4396e445976d4"`);
        await queryRunner.query(`ALTER TABLE "work_order_entity" DROP CONSTRAINT "FK_46907166ae6a4c26c13c4dd3083"`);
        await queryRunner.query(`ALTER TABLE "work_order_entity" DROP CONSTRAINT "FK_ced5736c7fe2fa52a344f6d2abb"`);
        await queryRunner.query(`ALTER TABLE "service_request_entity" DROP CONSTRAINT "FK_3d82297b1a61162ebab998fe8ee"`);
        await queryRunner.query(`ALTER TABLE "service_request_entity" DROP CONSTRAINT "FK_e72e2a6915d72117c8f9ca2c195"`);
        await queryRunner.query(`ALTER TABLE "service_request_entity" DROP CONSTRAINT "FK_5b2cadf701ee3a20b7c3dfd368d"`);
        await queryRunner.query(`ALTER TABLE "service_request_entity" DROP CONSTRAINT "FK_7973b8164ebee81efb2d3dea95a"`);
        await queryRunner.query(`ALTER TABLE "user_entity" DROP CONSTRAINT "FK_14e995b917d5c6bb8d2d4e9b546"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP COLUMN "SSMA_TimeStamp"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD "SSMA_TimeStamp" timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_1e1a1c7bbde58d1d9accda7c866" DEFAULT 0 FOR "LNGCLVQPM_PDT"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_3bd8bded47d258f20cfea432def" DEFAULT 0 FOR "LNGCLVMPL_PDT"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_eb00fdafc6c2c25a99d88919aba"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ALTER COLUMN "DTFCHPDT" datetime2(0)`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_580523d57b2cb59c3bf376e785c" DEFAULT 0 FOR "LNGCLVQPM_RGS"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_a8731d6aea6da718ee88b8ba0fe" DEFAULT 0 FOR "LNGCLVMPL_RGS"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "DF_54f3ecbc0dcb0ab6fc75975fc48"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ALTER COLUMN "DTFCHRGS" datetime2(0)`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_a87f8543bac64b3c42c98689b6a" DEFAULT 0 FOR "MNDIMPADQ"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_3ae82008596e745ab3b9dd9c557" DEFAULT 0 FOR "LNGCLVCHF"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_e8f84c29c6e03c619d9ec3b612e" DEFAULT 0 FOR "LNGCLVENT"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_289616fd56b2a1488d46c28f3ac" DEFAULT 0 FOR "LNGKLMVHC"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_3af4fa2fe5c31d4ad67e22fac96" DEFAULT 0 FOR "DCMPBRTRN"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP COLUMN "STRNSRTRN"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD "STRNSRTRN" nvarchar(17)`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD CONSTRAINT "DF_3f24815b7736116482437a866b3" DEFAULT 0 FOR "LNGCLVSTP"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ALTER COLUMN "STRCLVTPV" nvarchar(10) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP CONSTRAINT "PK_164f7f5ae561a5ae8f96953dd3d"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" DROP COLUMN "LNGDNTTRN"`);
        await queryRunner.query(`ALTER TABLE "TBLTRNVHC_CP" ADD "LNGDNTTRN" int NOT NULL IDENTITY(1,1)`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "DF_c2a36047c72d71b7d6c0d635c5f" DEFAULT 0 FOR "LNGCLVQPM_PDT"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "LNGCLVMPL_PDT"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "LNGCLVMPL_PDT" float`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "DF_50e8689f5343b41b3569fa6ef7b" DEFAULT 0 FOR "LNGCLVMPL_PDT"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "DTFCHPDT"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "DTFCHPDT" nvarchar(25)`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "DF_06b9e50b914f784b17ffa194bb7" DEFAULT 0 FOR "LNGCLVQPM_RGS"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "LNGCLVMPL_RGS"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "LNGCLVMPL_RGS" float`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "DF_a09f6241950cd294134034b0558" DEFAULT 0 FOR "LNGCLVMPL_RGS"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "DTFCHRGS"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "DTFCHRGS" nvarchar(25)`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "DF_9367a38e49f123e9b0de7ad84da" DEFAULT 0 FOR "LNGCLVMPL_BLQ"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "DF_13281011937dd948cc4b9ac3300" DEFAULT 0 FOR "BLNBLQRGS"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "DF_3c97cd8ff29381805a72e75c205" DEFAULT 0 FOR "Suspendido"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "DF_49dbd50580e9983db1ec9044de0" DEFAULT 0 FOR "DBLPRCDST"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRPWSEMP"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRPWSEMP" nvarchar(10)`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRNCKEMP"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRNCKEMP" nvarchar(50)`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "DF_e4d4c750aca056535da18661a2e" DEFAULT 0 FOR "BLNUSREMP"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRPSTEMP"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRPSTEMP" nvarchar(50)`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRDPTEMP"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRDPTEMP" nvarchar(50)`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRNSSEMP"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRNSSEMP" nvarchar(15)`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "STRLOCEMP"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "STRLOCEMP" nvarchar(50)`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "DF_2e58de69cf290138a0e962064c9" DEFAULT 0 FOR "LNGNOEMP"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP CONSTRAINT "PK_dc2b08a8089f60a105b512ba22a"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" DROP COLUMN "LNGCLVEMP"`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "LNGCLVEMP" int NOT NULL IDENTITY(1,1)`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD CONSTRAINT "PK_dc2b08a8089f60a105b512ba22a" PRIMARY KEY ("LNGCLVEMP")`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "SSMA_TimeStamp" timestamp NOT NULL`);
        await queryRunner.query(`ALTER TABLE "TBLCATEMP" ADD "Nombre" nvarchar(50)`);
        await queryRunner.query(`DROP TABLE "work_order_diagnostic_entity"`);
        await queryRunner.query(`DROP TABLE "work_order_service_entity"`);
        await queryRunner.query(`DROP TABLE "work_order_entity"`);
        await queryRunner.query(`DROP TABLE "service_request_entity"`);
        await queryRunner.query(`DROP TABLE "customer_entity"`);
        await queryRunner.query(`DROP TABLE "group_entity"`);
        await queryRunner.query(`DROP TABLE "user_entity"`);
        await queryRunner.query(`DROP TABLE "workshop_entity"`);
        await queryRunner.query(`DROP TABLE "workshop"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "TBLTRNVHC_CP$STRCLVTPV" ON "TBLTRNVHC_CP" ("STRCLVTPV") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "TBLTRNVHC_CP$LNGCLVSTP" ON "TBLTRNVHC_CP" ("LNGCLVSTP") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "TBLCATEMP$Id" ON "TBLCATEMP" ("LNGCLVEMP") `);
        await queryRunner.query(`CREATE INDEX "TBLCATEMP$ClientesIdClientes" ON "TBLCATEMP" ("LNGNOEMP") `);
    }

}
/* prettier-ignore */
