export enum ServiceRequestStatus {
  draft = 'draft',
  diagnostic_pending_approval = 'diagnostic_pending_approval',
  diagnostic_approved = 'diagnostic_approved',
  diagnostic_rejected = 'diagnostic_rejected',
  diagnostic_scheduled = 'diagnostic_scheduled',
  diagnostic_in_progress = 'diagnostic_in_progress',
  diagnostic_completed = 'diagnostic_completed',
}

// service_pending_approval = 'service_pending_approval',
// service_approved = 'service_approved',
// service_rejected = 'service_rejected',
// service_scheduled = 'service_scheduled',
// service_in_progress = 'service_in_progress',
// service_completed = 'service_completed',

// pending_approval = 'pending_approval',
// approved = 'approved',
// rejected = 'rejected',
// scheduled = 'scheduled',
// in_progress = 'in_progress',
// completed = 'completed',

// pending_review = 'pending_review',
// requested = 'requested',
// scheduled_diagnosis = 'scheduled_diagnosis',
// in_diagnosis = 'in_diagnosis',
// scheduled_service = 'scheduled_service',
// in_service = 'in_service',
// completed = 'completed',
